# Copyright 2015 Shuai Zhang
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[tools]
hk = "latest"
node = "22"
pnpm = "latest"
pkl = "latest"
typos = "latest"
go = "latest"
"go:github.com/B1NARY-GR0UP/nwa" = "latest"
ruby = "3.4"
