os: linux
dist: xenial

language: node_js

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "lts/*"

script:
  - npm run eslint
  - npm run jscs
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
